# Generated by Django 4.2 on 2023-04-29 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('slug', models.SlugField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Identify Number')),
                ('context', models.CharField(max_length=255)),
                ('intensity', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.SmallIntegerField(default=0, help_text='Does this timeblock cross days', verbose_name='Stetched Days')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='schedule.preset')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(blank=True, max_length=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedule.preset')),
                ('timeblock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.timeblock')),
            ],
        ),
    ]
