# Generated by Django 4.2 on 2023-04-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_preset_linked_alter_preset_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'OFF'), (1, 'SLEEP'), (2, 'WORK'), (3, 'WORK+'), (4, 'up-OVERNIGHT'), (5, 'OVERNIGHT')], default=0),
        ),
        migrations.AlterField(
            model_name='preset',
            name='linked',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule.preset'),
        ),
    ]
