# Generated by Django 4.2 on 2023-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_preset_intensity_alter_preset_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='preset',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'SLEEP'), (1, 'WORK'), (2, 'WORK+'), (3, '--OVERNIGHT'), (4, 'OVERNIGHT')], default=1),
        ),
        migrations.AlterField(
            model_name='preset',
            name='slug',
            field=models.SlugField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Call String'),
        ),
    ]
