# Generated by Django 4.2 on 2023-04-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_preset_context_alter_preset_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'SLEEP'), (1, 'WORK'), (2, 'WORK+'), (3, 'OVERNIGHT-bk'), (4, 'OVERNIGHT'), (5, 'OVERNIGHT-24')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedule.preset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeblock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.timeblock'),
        ),
    ]
