# Generated by Django 4.2 on 2023-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_preset_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'OFF'), (1, 'SLEEP'), (2, 'WORK'), (3, 'WORK+'), (4, 'OVERNIGHT-bk'), (5, 'OVERNIGHT'), (6, 'OVERNIGHT-24')], default=2),
        ),
    ]
