# Generated by Django 4.2 on 2023-05-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_preset_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='intensity',
            field=models.SmallIntegerField(default=2),
        ),
    ]
