# Generated by Django 4.2 on 2023-05-13 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0008_task_intensity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preset',
            new_name='Shift',
        ),
        migrations.AlterField(
            model_name='task',
            name='intensity',
            field=models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'SLEEP'), (2, 'WORK'), (3, 'WORK+'), (4, 'OVERNIGHT-bk'), (5, 'OVERNIGHT'), (6, 'OVERNIGHT-24')], default=2),
        ),
    ]
