# Generated by Django 4.2 on 2023-05-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0009_rename_preset_shift_alter_task_intensity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ['order', 'start_time']},
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='slug',
            new_name='call',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (3, 'OVERNIGHT'), (4, 'SLEEP')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='intensity',
            field=models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (3, 'OVERNIGHT'), (4, 'SLEEP')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeblock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.timeblock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='days',
            field=models.SmallIntegerField(default=0, help_text='(autofills 1 if start > end)', verbose_name='Stetched Days'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='schedule.shift'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='schedule.schedule')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
            preserve_default=False,
        ),
    ]
