# Generated by Django 4.2 on 2023-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_timeblock_options_rename_slug_shift_call_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeblock',
            old_name='preset',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='shift',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (2, 'BACKUP'), (3, 'OVERNIGHT'), (4, 'SLEEP')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='intensity',
            field=models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (2, 'BACKUP'), (3, 'OVERNIGHT'), (4, 'SLEEP')], default=2),
        ),
    ]
