# Generated by Django 4.2 on 2023-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_rename_preset_timeblock_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='available_at',
            field=models.PositiveIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (2, 'SLEEP'), (3, 'BACKUP'), (4, 'OVERNIGHT')], default=1, help_text='defines the maximum level of work that you are avaible at'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='intensity',
            field=models.PositiveIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (2, 'SLEEP'), (3, 'BACKUP'), (4, 'OVERNIGHT')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='intensity',
            field=models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'WORK'), (2, 'SLEEP'), (3, 'BACKUP'), (4, 'OVERNIGHT')], default=2),
        ),
    ]
