# Generated by Django 4.2 on 2023-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_schedule_available_at_alter_shift_intensity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='context',
        ),
        migrations.AddField(
            model_name='task',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
