# Generated by Django 4.2 on 2023-05-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_schedule_name_alter_task_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=63)),
                ('color', models.CharField(default='#FFFFFF',  max_length=18)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='available_at',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='intensity',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=18, null=True,),
        ),
        migrations.AlterField(
            model_name='shift',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='off_work_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.workkey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.workkey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='work_key',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.workkey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='work_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.workkey'),
            preserve_default=False,
        ),
    ]
