# Generated by Django 4.2 on 2023-05-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_workkey_remove_schedule_available_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeblock',
            old_name='schedule',
            new_name='Shift',
        ),
    ]
