# Generated by Django 4.2 on 2023-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_rename_schedule_timeblock_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='workkey',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=18),
        ),
    ]
