# Generated by Django 4.2 on 2023-05-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_shift_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='linked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule.shift', verbose_name='linked_after'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='work_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule.workkey'),
        ),
    ]
