# Generated by Django 4.2 on 2023-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_alter_shift_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='dependent',
            new_name='dependent_on',
        ),
    ]
